var itemPrice={
  'Normal':300,
  'Thin Crust':350,
  'Anchovies':50,
  'Bacon':100,
  'Canadian Bacon':150,
  'Chicken':100,
  'Italian Sausage':175,
  'Sausage':125,
  'Pepperoni':90,
  'Green Pepper':50,
  'Mushrooms':25,
  'Onions':30,
  'Tomatoes':30,
  'Banana Peppers':70,
  'Pineapple TitBits':65,
  'Ripe Olives':95,
  'Green Olives':90,
  'Jaapeno Peppers':75,
  'Parmesan/Romano':100,
  'Three Cheese Blend':150,
  'Chicken BBQ Pizza Sauce':80,
  'Ranch Sauce':70,
  'Spinach Alfredo Sauce':75,
  'Chicken Poppers':200,
  'Chicken Wings(Roasted)':250,
  'Chocolate Chip Cookie':150,
  'Double Chocolate Chip Brownie':200,
  'Pepperoncia':25,
  'BBQ Dipping Sauce':25,
  'Blue Cheese Dipping Sauce':25,
  'Buffalo Dipping Sauce':25,
  'Cheese Dipping Sauce':25,
  'Garlic Sauce':25,
  'Garlic Parmesan Sauce':25,
  'Honey Chipotle Sauce':25,
  'customize':'pizza',
  'extras_pizza':'extras',
  'sides_D':'sides_Dessert'
};
